apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: worker
  name: worker
  namespace: lab5
spec:
  containers:
  - image: nginx
    name: worker
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
